//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBTFull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Abu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Abu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBTFull.Resources.Abu", typeof(Abu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirTitle].
        /// </summary>
        public static string AbuCompressedAirTitle {
            get {
                return ResourceManager.GetString("AbuCompressedAirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue1].
        /// </summary>
        public static string AbuCompressedAirValue1 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue2].
        /// </summary>
        public static string AbuCompressedAirValue2 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue2.1].
        /// </summary>
        public static string AbuCompressedAirValue21 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue2.2].
        /// </summary>
        public static string AbuCompressedAirValue22 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue2.3].
        /// </summary>
        public static string AbuCompressedAirValue23 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue2.4].
        /// </summary>
        public static string AbuCompressedAirValue24 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue3].
        /// </summary>
        public static string AbuCompressedAirValue3 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue4].
        /// </summary>
        public static string AbuCompressedAirValue4 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuCompressedAirValue5].
        /// </summary>
        public static string AbuCompressedAirValue5 {
            get {
                return ResourceManager.GetString("AbuCompressedAirValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuDimensions{0}].
        /// </summary>
        public static string AbuDimensions {
            get {
                return ResourceManager.GetString("AbuDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricalConsumptionTitle].
        /// </summary>
        public static string AbuElectricalConsumptionTitle {
            get {
                return ResourceManager.GetString("AbuElectricalConsumptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricalConsumptionValue1{0}{1}].
        /// </summary>
        public static string AbuElectricalConsumptionValue1 {
            get {
                return ResourceManager.GetString("AbuElectricalConsumptionValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricalConsumptionValue2{0}].
        /// </summary>
        public static string AbuElectricalConsumptionValue2 {
            get {
                return ResourceManager.GetString("AbuElectricalConsumptionValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricalConsumptionValue3{0}].
        /// </summary>
        public static string AbuElectricalConsumptionValue3 {
            get {
                return ResourceManager.GetString("AbuElectricalConsumptionValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricalConsumptionValue4{0}].
        /// </summary>
        public static string AbuElectricalConsumptionValue4 {
            get {
                return ResourceManager.GetString("AbuElectricalConsumptionValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityTitle].
        /// </summary>
        public static string AbuElectricityTitle {
            get {
                return ResourceManager.GetString("AbuElectricityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1].
        /// </summary>
        public static string AbuElectricityValue1 {
            get {
                return ResourceManager.GetString("AbuElectricityValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1.1{0}].
        /// </summary>
        public static string AbuElectricityValue11 {
            get {
                return ResourceManager.GetString("AbuElectricityValue11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1.2{0}].
        /// </summary>
        public static string AbuElectricityValue12 {
            get {
                return ResourceManager.GetString("AbuElectricityValue12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1.3{0}].
        /// </summary>
        public static string AbuElectricityValue13 {
            get {
                return ResourceManager.GetString("AbuElectricityValue13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1.4].
        /// </summary>
        public static string AbuElectricityValue14 {
            get {
                return ResourceManager.GetString("AbuElectricityValue14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1.5].
        /// </summary>
        public static string AbuElectricityValue15 {
            get {
                return ResourceManager.GetString("AbuElectricityValue15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue1.6].
        /// </summary>
        public static string AbuElectricityValue16 {
            get {
                return ResourceManager.GetString("AbuElectricityValue16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue2].
        /// </summary>
        public static string AbuElectricityValue2 {
            get {
                return ResourceManager.GetString("AbuElectricityValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue3].
        /// </summary>
        public static string AbuElectricityValue3 {
            get {
                return ResourceManager.GetString("AbuElectricityValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue4].
        /// </summary>
        public static string AbuElectricityValue4 {
            get {
                return ResourceManager.GetString("AbuElectricityValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuElectricityValue5].
        /// </summary>
        public static string AbuElectricityValue5 {
            get {
                return ResourceManager.GetString("AbuElectricityValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationTitle1{0}].
        /// </summary>
        public static string AbuInstallationTitle1 {
            get {
                return ResourceManager.GetString("AbuInstallationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationTitle2].
        /// </summary>
        public static string AbuInstallationTitle2 {
            get {
                return ResourceManager.GetString("AbuInstallationTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue1].
        /// </summary>
        public static string AbuInstallationValue1 {
            get {
                return ResourceManager.GetString("AbuInstallationValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue2{0}].
        /// </summary>
        public static string AbuInstallationValue2 {
            get {
                return ResourceManager.GetString("AbuInstallationValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue3].
        /// </summary>
        public static string AbuInstallationValue3 {
            get {
                return ResourceManager.GetString("AbuInstallationValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue4].
        /// </summary>
        public static string AbuInstallationValue4 {
            get {
                return ResourceManager.GetString("AbuInstallationValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue4.1].
        /// </summary>
        public static string AbuInstallationValue41 {
            get {
                return ResourceManager.GetString("AbuInstallationValue41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue5].
        /// </summary>
        public static string AbuInstallationValue5 {
            get {
                return ResourceManager.GetString("AbuInstallationValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue6].
        /// </summary>
        public static string AbuInstallationValue6 {
            get {
                return ResourceManager.GetString("AbuInstallationValue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationValue7].
        /// </summary>
        public static string AbuInstallationValue7 {
            get {
                return ResourceManager.GetString("AbuInstallationValue7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuLifespanTitle].
        /// </summary>
        public static string AbuLifespanTitle {
            get {
                return ResourceManager.GetString("AbuLifespanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuLifespanValue].
        /// </summary>
        public static string AbuLifespanValue {
            get {
                return ResourceManager.GetString("AbuLifespanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuMaintenanceTitle{0}].
        /// </summary>
        public static string AbuMaintenanceTitle {
            get {
                return ResourceManager.GetString("AbuMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuMaintenanceValue].
        /// </summary>
        public static string AbuMaintenanceValue {
            get {
                return ResourceManager.GetString("AbuMaintenanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuPhenolEfficiencyTitle].
        /// </summary>
        public static string AbuPhenolEfficiencyTitle {
            get {
                return ResourceManager.GetString("AbuPhenolEfficiencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuPhenolEfficiencyValue{0}{1}].
        /// </summary>
        public static string AbuPhenolEfficiencyValue {
            get {
                return ResourceManager.GetString("AbuPhenolEfficiencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSpecTitle].
        /// </summary>
        public static string AbuSpecTitle {
            get {
                return ResourceManager.GetString("AbuSpecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbutDrainageTitle].
        /// </summary>
        public static string AbutDrainageTitle {
            get {
                return ResourceManager.GetString("AbutDrainageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbutDrainageValue1].
        /// </summary>
        public static string AbutDrainageValue1 {
            get {
                return ResourceManager.GetString("AbutDrainageValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbutDrainageValue2].
        /// </summary>
        public static string AbutDrainageValue2 {
            get {
                return ResourceManager.GetString("AbutDrainageValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbutDrainageValue3].
        /// </summary>
        public static string AbutDrainageValue3 {
            get {
                return ResourceManager.GetString("AbutDrainageValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbutDrainageValue4].
        /// </summary>
        public static string AbutDrainageValue4 {
            get {
                return ResourceManager.GetString("AbutDrainageValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbutDrainageValue5].
        /// </summary>
        public static string AbutDrainageValue5 {
            get {
                return ResourceManager.GetString("AbutDrainageValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTitle{0}{1}].
        /// </summary>
        public static string AbuTitle {
            get {
                return ResourceManager.GetString("AbuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTriethylamineEfficiencyTitle].
        /// </summary>
        public static string AbuTriethylamineEfficiencyTitle {
            get {
                return ResourceManager.GetString("AbuTriethylamineEfficiencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTriethylamineEfficiencyValue1].
        /// </summary>
        public static string AbuTriethylamineEfficiencyValue1 {
            get {
                return ResourceManager.GetString("AbuTriethylamineEfficiencyValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTriethylamineEfficiencyValue2].
        /// </summary>
        public static string AbuTriethylamineEfficiencyValue2 {
            get {
                return ResourceManager.GetString("AbuTriethylamineEfficiencyValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTriethylamineEfficiencyValue3].
        /// </summary>
        public static string AbuTriethylamineEfficiencyValue3 {
            get {
                return ResourceManager.GetString("AbuTriethylamineEfficiencyValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTriethylamineEfficiencyValue4].
        /// </summary>
        public static string AbuTriethylamineEfficiencyValue4 {
            get {
                return ResourceManager.GetString("AbuTriethylamineEfficiencyValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTriethylamineEfficiencyValue5{0}{1}{2}].
        /// </summary>
        public static string AbuTriethylamineEfficiencyValue5 {
            get {
                return ResourceManager.GetString("AbuTriethylamineEfficiencyValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationTitle].
        /// </summary>
        public static string AbuVentilationTitle {
            get {
                return ResourceManager.GetString("AbuVentilationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue1].
        /// </summary>
        public static string AbuVentilationValue1 {
            get {
                return ResourceManager.GetString("AbuVentilationValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue1.1].
        /// </summary>
        public static string AbuVentilationValue11 {
            get {
                return ResourceManager.GetString("AbuVentilationValue11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue1.2].
        /// </summary>
        public static string AbuVentilationValue12 {
            get {
                return ResourceManager.GetString("AbuVentilationValue12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue1.3].
        /// </summary>
        public static string AbuVentilationValue13 {
            get {
                return ResourceManager.GetString("AbuVentilationValue13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue2{0}].
        /// </summary>
        public static string AbuVentilationValue2 {
            get {
                return ResourceManager.GetString("AbuVentilationValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue2.1{0}{1}].
        /// </summary>
        public static string AbuVentilationValue21 {
            get {
                return ResourceManager.GetString("AbuVentilationValue21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue2.2].
        /// </summary>
        public static string AbuVentilationValue22 {
            get {
                return ResourceManager.GetString("AbuVentilationValue22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue2.3{0}].
        /// </summary>
        public static string AbuVentilationValue23 {
            get {
                return ResourceManager.GetString("AbuVentilationValue23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue2.4{0}].
        /// </summary>
        public static string AbuVentilationValue24 {
            get {
                return ResourceManager.GetString("AbuVentilationValue24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue2.5].
        /// </summary>
        public static string AbuVentilationValue25 {
            get {
                return ResourceManager.GetString("AbuVentilationValue25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue3].
        /// </summary>
        public static string AbuVentilationValue3 {
            get {
                return ResourceManager.GetString("AbuVentilationValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue4].
        /// </summary>
        public static string AbuVentilationValue4 {
            get {
                return ResourceManager.GetString("AbuVentilationValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuVentilationValue4.1].
        /// </summary>
        public static string AbuVentilationValue41 {
            get {
                return ResourceManager.GetString("AbuVentilationValue41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyTitle].
        /// </summary>
        public static string AbuWaterSupplyTitle {
            get {
                return ResourceManager.GetString("AbuWaterSupplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue1].
        /// </summary>
        public static string AbuWaterSupplyValue1 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue2].
        /// </summary>
        public static string AbuWaterSupplyValue2 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue3].
        /// </summary>
        public static string AbuWaterSupplyValue3 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue3.1].
        /// </summary>
        public static string AbuWaterSupplyValue31 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue3.2].
        /// </summary>
        public static string AbuWaterSupplyValue32 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue3.3].
        /// </summary>
        public static string AbuWaterSupplyValue33 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue3.4].
        /// </summary>
        public static string AbuWaterSupplyValue34 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue4].
        /// </summary>
        public static string AbuWaterSupplyValue4 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuWaterSupplyValue5].
        /// </summary>
        public static string AbuWaterSupplyValue5 {
            get {
                return ResourceManager.GetString("AbuWaterSupplyValue5", resourceCulture);
            }
        }
    }
}
