//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBTFull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Advantages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advantages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBTFull.Resources.Advantages", typeof(Advantages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AduAdvantages].
        /// </summary>
        public static string AduAdvantages {
            get {
                return ResourceManager.GetString("AduAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage1].
        /// </summary>
        public static string Advantage1 {
            get {
                return ResourceManager.GetString("Advantage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage10Description].
        /// </summary>
        public static string Advantage10Description {
            get {
                return ResourceManager.GetString("Advantage10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage10Title].
        /// </summary>
        public static string Advantage10Title {
            get {
                return ResourceManager.GetString("Advantage10Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage1Description].
        /// </summary>
        public static string Advantage1Description {
            get {
                return ResourceManager.GetString("Advantage1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage1Title].
        /// </summary>
        public static string Advantage1Title {
            get {
                return ResourceManager.GetString("Advantage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage2].
        /// </summary>
        public static string Advantage2 {
            get {
                return ResourceManager.GetString("Advantage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage2Description].
        /// </summary>
        public static string Advantage2Description {
            get {
                return ResourceManager.GetString("Advantage2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage2Title].
        /// </summary>
        public static string Advantage2Title {
            get {
                return ResourceManager.GetString("Advantage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage3].
        /// </summary>
        public static string Advantage3 {
            get {
                return ResourceManager.GetString("Advantage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage3Description].
        /// </summary>
        public static string Advantage3Description {
            get {
                return ResourceManager.GetString("Advantage3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage3Title].
        /// </summary>
        public static string Advantage3Title {
            get {
                return ResourceManager.GetString("Advantage3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage4].
        /// </summary>
        public static string Advantage4 {
            get {
                return ResourceManager.GetString("Advantage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage4Description].
        /// </summary>
        public static string Advantage4Description {
            get {
                return ResourceManager.GetString("Advantage4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage4Title].
        /// </summary>
        public static string Advantage4Title {
            get {
                return ResourceManager.GetString("Advantage4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage5].
        /// </summary>
        public static string Advantage5 {
            get {
                return ResourceManager.GetString("Advantage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage5Description].
        /// </summary>
        public static string Advantage5Description {
            get {
                return ResourceManager.GetString("Advantage5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage5Title].
        /// </summary>
        public static string Advantage5Title {
            get {
                return ResourceManager.GetString("Advantage5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage6].
        /// </summary>
        public static string Advantage6 {
            get {
                return ResourceManager.GetString("Advantage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage6Description].
        /// </summary>
        public static string Advantage6Description {
            get {
                return ResourceManager.GetString("Advantage6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage6Title].
        /// </summary>
        public static string Advantage6Title {
            get {
                return ResourceManager.GetString("Advantage6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage7].
        /// </summary>
        public static string Advantage7 {
            get {
                return ResourceManager.GetString("Advantage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage7Description].
        /// </summary>
        public static string Advantage7Description {
            get {
                return ResourceManager.GetString("Advantage7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage7Title].
        /// </summary>
        public static string Advantage7Title {
            get {
                return ResourceManager.GetString("Advantage7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage8].
        /// </summary>
        public static string Advantage8 {
            get {
                return ResourceManager.GetString("Advantage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage8Description1].
        /// </summary>
        public static string Advantage8Description1 {
            get {
                return ResourceManager.GetString("Advantage8Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage8Description2].
        /// </summary>
        public static string Advantage8Description2 {
            get {
                return ResourceManager.GetString("Advantage8Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage8Title].
        /// </summary>
        public static string Advantage8Title {
            get {
                return ResourceManager.GetString("Advantage8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage9].
        /// </summary>
        public static string Advantage9 {
            get {
                return ResourceManager.GetString("Advantage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage9Description].
        /// </summary>
        public static string Advantage9Description {
            get {
                return ResourceManager.GetString("Advantage9Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantage9Title].
        /// </summary>
        public static string Advantage9Title {
            get {
                return ResourceManager.GetString("Advantage9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [9ReasonsToChooseAbu].
        /// </summary>
        public static string NineReasonsToChooseAbu {
            get {
                return ResourceManager.GetString("NineReasonsToChooseAbu", resourceCulture);
            }
        }
    }
}
