//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBTFull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Faq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Faq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBTFull.Resources.Faq", typeof(Faq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer1].
        /// </summary>
        public static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer10].
        /// </summary>
        public static string Answer10 {
            get {
                return ResourceManager.GetString("Answer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer11].
        /// </summary>
        public static string Answer11 {
            get {
                return ResourceManager.GetString("Answer11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer12].
        /// </summary>
        public static string Answer12 {
            get {
                return ResourceManager.GetString("Answer12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer13].
        /// </summary>
        public static string Answer13 {
            get {
                return ResourceManager.GetString("Answer13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer14].
        /// </summary>
        public static string Answer14 {
            get {
                return ResourceManager.GetString("Answer14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer15].
        /// </summary>
        public static string Answer15 {
            get {
                return ResourceManager.GetString("Answer15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer2].
        /// </summary>
        public static string Answer2 {
            get {
                return ResourceManager.GetString("Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer3].
        /// </summary>
        public static string Answer3 {
            get {
                return ResourceManager.GetString("Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer4].
        /// </summary>
        public static string Answer4 {
            get {
                return ResourceManager.GetString("Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer5.1].
        /// </summary>
        public static string Answer5_1 {
            get {
                return ResourceManager.GetString("Answer5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer5.2].
        /// </summary>
        public static string Answer5_2 {
            get {
                return ResourceManager.GetString("Answer5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer6].
        /// </summary>
        public static string Answer6 {
            get {
                return ResourceManager.GetString("Answer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer7].
        /// </summary>
        public static string Answer7 {
            get {
                return ResourceManager.GetString("Answer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer8].
        /// </summary>
        public static string Answer8 {
            get {
                return ResourceManager.GetString("Answer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer9.1].
        /// </summary>
        public static string Answer9_1 {
            get {
                return ResourceManager.GetString("Answer9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Answer9.2].
        /// </summary>
        public static string Answer9_2 {
            get {
                return ResourceManager.GetString("Answer9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question1].
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question10].
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question11].
        /// </summary>
        public static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question12].
        /// </summary>
        public static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question13].
        /// </summary>
        public static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question14].
        /// </summary>
        public static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question15].
        /// </summary>
        public static string Question15 {
            get {
                return ResourceManager.GetString("Question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question2].
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question3].
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question4].
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question5].
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question6].
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question7].
        /// </summary>
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question8].
        /// </summary>
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Question9].
        /// </summary>
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
    }
}
