//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBTFull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBTFull.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuEfficiency].
        /// </summary>
        public static string AbuEfficiency {
            get {
                return ResourceManager.GetString("AbuEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuEfficiencyFormol].
        /// </summary>
        public static string AbuEfficiencyFormol {
            get {
                return ResourceManager.GetString("AbuEfficiencyFormol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuEfficiencyResin].
        /// </summary>
        public static string AbuEfficiencyResin {
            get {
                return ResourceManager.GetString("AbuEfficiencyResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuEfficiencyResinValue{0}].
        /// </summary>
        public static string AbuEfficiencyResinValue {
            get {
                return ResourceManager.GetString("AbuEfficiencyResinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuEfficiencyTriethylamine].
        /// </summary>
        public static string AbuEfficiencyTriethylamine {
            get {
                return ResourceManager.GetString("AbuEfficiencyTriethylamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuEfficiencyTriethylamineValue].
        /// </summary>
        public static string AbuEfficiencyTriethylamineValue {
            get {
                return ResourceManager.GetString("AbuEfficiencyTriethylamineValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuIntro].
        /// </summary>
        public static string AbuIntro {
            get {
                return ResourceManager.GetString("AbuIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOperationDescription].
        /// </summary>
        public static string AbuOperationDescription {
            get {
                return ResourceManager.GetString("AbuOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOperationDetailsOne].
        /// </summary>
        public static string AbuOperationDetailsOne {
            get {
                return ResourceManager.GetString("AbuOperationDetailsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOperationDetailsThree].
        /// </summary>
        public static string AbuOperationDetailsThree {
            get {
                return ResourceManager.GetString("AbuOperationDetailsThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOperationDetailsTwo].
        /// </summary>
        public static string AbuOperationDetailsTwo {
            get {
                return ResourceManager.GetString("AbuOperationDetailsTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationTitle].
        /// </summary>
        public static string AbuOprationTitle {
            get {
                return ResourceManager.GetString("AbuOprationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueA].
        /// </summary>
        public static string AbuOprationValueA {
            get {
                return ResourceManager.GetString("AbuOprationValueA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueB].
        /// </summary>
        public static string AbuOprationValueB {
            get {
                return ResourceManager.GetString("AbuOprationValueB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueC].
        /// </summary>
        public static string AbuOprationValueC {
            get {
                return ResourceManager.GetString("AbuOprationValueC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueFour].
        /// </summary>
        public static string AbuOprationValueFour {
            get {
                return ResourceManager.GetString("AbuOprationValueFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueOne].
        /// </summary>
        public static string AbuOprationValueOne {
            get {
                return ResourceManager.GetString("AbuOprationValueOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueThree].
        /// </summary>
        public static string AbuOprationValueThree {
            get {
                return ResourceManager.GetString("AbuOprationValueThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuOprationValueTwo].
        /// </summary>
        public static string AbuOprationValueTwo {
            get {
                return ResourceManager.GetString("AbuOprationValueTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuPurificationDescriptionOne].
        /// </summary>
        public static string AbuPurificationDescriptionOne {
            get {
                return ResourceManager.GetString("AbuPurificationDescriptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuPurificationDescriptionTwo].
        /// </summary>
        public static string AbuPurificationDescriptionTwo {
            get {
                return ResourceManager.GetString("AbuPurificationDescriptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuPurificationTitle].
        /// </summary>
        public static string AbuPurificationTitle {
            get {
                return ResourceManager.GetString("AbuPurificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbyEfficiencyDescription].
        /// </summary>
        public static string AbyEfficiencyDescription {
            get {
                return ResourceManager.GetString("AbyEfficiencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CompanyIntro].
        /// </summary>
        public static string CompanyIntro {
            get {
                return ResourceManager.GetString("CompanyIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Concentration{0}{1}].
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IndexTitle].
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
    }
}
