//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBTFull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBTFull.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Abu{0}].
        /// </summary>
        public static string Abu {
            get {
                return ResourceManager.GetString("Abu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [abuSpecsFilename].
        /// </summary>
        public static string abuSpecsFilename {
            get {
                return ResourceManager.GetString("abuSpecsFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advantages].
        /// </summary>
        public static string Advantages {
            get {
                return ResourceManager.GetString("Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Contacts].
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EnquiriesLink].
        /// </summary>
        public static string EnquiriesLink {
            get {
                return ResourceManager.GetString("EnquiriesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Faq].
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FaqLink].
        /// </summary>
        public static string FaqLink {
            get {
                return ResourceManager.GetString("FaqLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ForDesigners].
        /// </summary>
        public static string ForDesigners {
            get {
                return ResourceManager.GetString("ForDesigners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MainPage].
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NoviSad].
        /// </summary>
        public static string NoviSad {
            get {
                return ResourceManager.GetString("NoviSad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Questioneer].
        /// </summary>
        public static string questioneer {
            get {
                return ResourceManager.GetString("questioneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Serbia].
        /// </summary>
        public static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ближайшее время мы с Вами свяжемся..
        /// </summary>
        public static string ThankYouMessage1 {
            get {
                return ResourceManager.GetString("ThankYouMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, Ваше сообщение получено..
        /// </summary>
        public static string ThankYouMessage2 {
            get {
                return ResourceManager.GetString("ThankYouMessage2", resourceCulture);
            }
        }
    }
}
