//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBTFull.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Views_Home_Engineering {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Engineering() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBTFull.Resources.Views.Home.Engineering", typeof(Views_Home_Engineering).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuDescription1].
        /// </summary>
        public static string AbuDescription1 {
            get {
                return ResourceManager.GetString("AbuDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuDescription2].
        /// </summary>
        public static string AbuDescription2 {
            get {
                return ResourceManager.GetString("AbuDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuDescription3].
        /// </summary>
        public static string AbuDescription3 {
            get {
                return ResourceManager.GetString("AbuDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuDescription4].
        /// </summary>
        public static string AbuDescription4 {
            get {
                return ResourceManager.GetString("AbuDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuDescription5].
        /// </summary>
        public static string AbuDescription5 {
            get {
                return ResourceManager.GetString("AbuDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationListItem1].
        /// </summary>
        public static string AbuInstallationListItem1 {
            get {
                return ResourceManager.GetString("AbuInstallationListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationListItem2].
        /// </summary>
        public static string AbuInstallationListItem2 {
            get {
                return ResourceManager.GetString("AbuInstallationListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuInstallationListTitle].
        /// </summary>
        public static string AbuInstallationListTitle {
            get {
                return ResourceManager.GetString("AbuInstallationListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuMoreDetails].
        /// </summary>
        public static string AbuMoreDetails {
            get {
                return ResourceManager.GetString("AbuMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableHeader1].
        /// </summary>
        public static string AbuParametersTableHeader1 {
            get {
                return ResourceManager.GetString("AbuParametersTableHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableHeader2].
        /// </summary>
        public static string AbuParametersTableHeader2 {
            get {
                return ResourceManager.GetString("AbuParametersTableHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow1Value1].
        /// </summary>
        public static string AbuParametersTableRow1Value1 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow1Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow2Value1].
        /// </summary>
        public static string AbuParametersTableRow2Value1 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow2Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow2Value2].
        /// </summary>
        public static string AbuParametersTableRow2Value2 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow2Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow2Value3].
        /// </summary>
        public static string AbuParametersTableRow2Value3 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow2Value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow3Value1].
        /// </summary>
        public static string AbuParametersTableRow3Value1 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow3Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow4Value1].
        /// </summary>
        public static string AbuParametersTableRow4Value1 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow4Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow5Value1].
        /// </summary>
        public static string AbuParametersTableRow5Value1 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow5Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTableRow6Value1].
        /// </summary>
        public static string AbuParametersTableRow6Value1 {
            get {
                return ResourceManager.GetString("AbuParametersTableRow6Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuParametersTitle].
        /// </summary>
        public static string AbuParametersTitle {
            get {
                return ResourceManager.GetString("AbuParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaTitle].
        /// </summary>
        public static string AbuSchemaTitle {
            get {
                return ResourceManager.GetString("AbuSchemaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaValue1].
        /// </summary>
        public static string AbuSchemaValue1 {
            get {
                return ResourceManager.GetString("AbuSchemaValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaValue2].
        /// </summary>
        public static string AbuSchemaValue2 {
            get {
                return ResourceManager.GetString("AbuSchemaValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaValue3].
        /// </summary>
        public static string AbuSchemaValue3 {
            get {
                return ResourceManager.GetString("AbuSchemaValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaValue4].
        /// </summary>
        public static string AbuSchemaValue4 {
            get {
                return ResourceManager.GetString("AbuSchemaValue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaValue5].
        /// </summary>
        public static string AbuSchemaValue5 {
            get {
                return ResourceManager.GetString("AbuSchemaValue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuSchemaValue6].
        /// </summary>
        public static string AbuSchemaValue6 {
            get {
                return ResourceManager.GetString("AbuSchemaValue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTemperatureParameters1].
        /// </summary>
        public static string AbuTemperatureParameters1 {
            get {
                return ResourceManager.GetString("AbuTemperatureParameters1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AbuTemperatureParameters2].
        /// </summary>
        public static string AbuTemperatureParameters2 {
            get {
                return ResourceManager.GetString("AbuTemperatureParameters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CatalogTitle].
        /// </summary>
        public static string CatalogTitle {
            get {
                return ResourceManager.GetString("CatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Complex].
        /// </summary>
        public static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Distributed].
        /// </summary>
        public static string Distributed {
            get {
                return ResourceManager.GetString("Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Single].
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
    }
}
